---
- name: Add user 
  shell: useradd zammad -m -d /opt/zammad -s /bin/bash

- name: Download artifacts 
  get_url:
    url: https://ftp.zammad.com/zammad-latest.tar.gz
    dest: /opt

- name: unarchive tar 
  unarchive:
    src: /opt/zammad-latest.tar.gz
    dest: /opt/zammad

- name: Install deps  
  shell: "{{ item }}"
  with_items:
    - "gem install bundler rake rails"
    - "bundle install --without test development postgres"

- name : Install
  shell: |
     export RAILS_ENV=production
     export RAILS_SERVE_STATIC_FILES=true
     rake db:create
     rake db:migrate
     rake db:seed
     rake assets:precompile
     rails s -p 3000 & 


  