---
# name: deploy_freepbx

deploy_freepbx_packages: [ lynx, tftp-server, unixODBC, mysql-connector-odbc, mariadb-server, mariadb, httpd, ncurses-devel, sendmail, sendmail-cf, sox, newt-devel, libxml2-devel, libtiff-devel, audiofile-devel, gtk2-devel, subversion, kernel-devel, git, crontabs, cronie, cronie-anacron, wget, vim, uuid-devel, sqlite-devel, net-tools, gnutls-devel, python-devel, texinfo, mod_ssl ]

deploy_freepbx_extra_repos:
  - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  - https://rpm.nodesource.com/pub_8.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm

deploy_freepbx_php56: [ php56w, php56w-pdo, php56w-mysql, php56w-mbstring, php56w-pear, php56w-process, php56w-xml, php56w-opcache, php56w-ldap, php56w-intl, php56w-soap ]

deploy_freepbx_web_db: [ mariadb, httpd ]

deploy_freepbx_jansson_packages:
  - https://github.com/akheron/jansson/archive/v2.11.tar.gz

deploy_freepbx_asterisk_packages:
  - http://downloads.asterisk.org/pub/telephony/libpri/libpri-current.tar.gz
  - http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-13-current.tar.gz

deploy_freepbx_freepbx_packages:
  - http://mirror.freepbx.org/modules/packages/freepbx/freepbx-14.0-latest.tgz

deploy_freepbx_php_memory_limit: "512M"      # Custom memory limit configured within /etc/php.d/freepbx.ini
