---
## Freepbx

- name: Pull down Freepbx
  unarchive:
    src: "{{ item }}"
    dest: /usr/src
    remote_src: yes
  with_items: "{{ deploy_freepbx_freepbx_packages }}"

- name: Run install for Freepbx
  command: "{{ item.command }}"
  args:
    chdir: "/usr/src/freepbx"
    creates: "{{ item.creates }}"
  with_items:
    - { command: './start_asterisk start', creates: "/var/www/html/admin/" }
    - { command: './install -n', creates: "/var/www/html/admin/" }

- name: Make Freepbx service template
  template:
    src: freepbx.service.j2
    dest: "/etc/systemd/system/freepbx.service"
  notify: restart_freepbx

- name: Configure Apache with specific Freepbx Options
  replace:
    path: /etc/httpd/conf/httpd.conf
    regexp: 'AllowOverride None'
    replace: 'AllowOverride All'
  notify: restart_apache

- name: Configure Apache with specific Freepbx Options
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { path: '/etc/httpd/conf/httpd.conf', line: 'User asterisk', regexp: '^User ' }
    - { path: '/etc/httpd/conf/httpd.conf', line: 'Group asterisk', regexp: '^Group ' }

- name: Create custom PHP ini
  template:
    src: freepbx.ini.j2
    dest: "/etc/php.d/freepbx.ini"
  notify: restart_apache

- name: Enable freepbx service
  service:
    name: "freepbx"
    enabled: yes
